### PR TITLE
New Updates-Replaced promises with async await, recoded and fixed bug…

### PR DESCRIPTION
**Pull request by ShreshthTiwari**
…s i could find, created separate modules for calculation, made the packages integrity check better, updated packages version

### CODE REVIEW

**Comment by PM-KIRILL** [comment]
There is a bug where unknown numbers are displayed instead of ram and disk
IMG_20230731_040305

**Comment by ShreshthTiwari** [comment]
> There is a bug where unknown numbers are displayed instead of ram and disk IMG_20230731_040305

How is this shet related to my new PR

**Review by NxyyLOL — APPROVED** [review]
its good

**Comment by ShreshthTiwari** [comment]
> its good

lol when aprrove?

**Review by HirziDevs — APPROVED** [review]

**Pull request merged**
