### PR TITLE
Update pterostats-egg.json

### PR DESCRIPTION
**Pull request by EthanSpleefan**
Fix PteroStats egg

Serer Error 500 when uploading due to rules str and "sort" column.

Not sure if its just me but I'm having errors with installing the egg and after using the logs to debug I made these changes now it works.

### CODE REVIEW

**Comment by EthanSpleefan** [comment]
image
Success

**Comment by lezetho** [comment]
hm, i don't think it originally was using commas as it worked fine on my local machine.  try using this egg (attached below)

[egg-ptero-stats.json](https://github.com/user-attachments/files/17702284/egg-ptero-stats.json)

**Comment by EthanSpleefan** [comment]
> hm, i don't think it originally was using commas as it worked fine on my local machine. try using this egg (attached below)
> 
> [egg-ptero-stats.json](https://github.com/user-attachments/files/17702284/egg-ptero-stats.json)

That's not the egg on the main repo, i have got it installed and working now.

**Comment by EthanSpleefan** [comment]
image

**Comment by EthanSpleefan** [comment]
> > hm, i don't think it originally was using commas as it worked fine on my local machine. try using this egg (attached below)
> > [egg-ptero-stats.json](https://github.com/user-attachments/files/17702284/egg-ptero-stats.json)
> 
> That's not the egg on the main repo, i have got it installed and working now.

As In the script i setup is working.

**Comment by lezetho** [comment]
> > hm, i don't think it originally was using commas as it worked fine on my local machine. try using this egg (attached below)
> > [egg-ptero-stats.json](https://github.com/user-attachments/files/17702284/egg-ptero-stats.json)
> 
> That's not the egg on the main repo, i have got it installed and working now.

Correct as @HirziDevs hasn't had time to update it to the main repo. Currently the Discord has the updated version.

**Comment by HirziDevs** [comment]
> > hm, i don't think it originally was using commas as it worked fine on my local machine. try using this egg (attached below)
> > [egg-ptero-stats.json](https://github.com/user-attachments/files/17702284/egg-ptero-stats.json)
> 
> That's not the egg on the main repo, i have got it installed and working now.

It was the egg from discord, i import it to my pelican panel first and export it again and upload it to the main repo, maybe thats why the egg doesn't work for pterodactyl

**Review by HirziDevs — APPROVED** [review]

**Pull request merged**
