### PR TITLE
feat: Docker Image

### PR DESCRIPTION
**Pull request by PandeoF1**
Hello, this little PR add a simple docker image to permit the usage of the bot in egg/docker environment !

I have also added a workflow to generate the docker image when a tag is released.

### CODE REVIEW

**Review by lezetho — APPROVED** [review]
Very nice, looks good, I don't see any major flaws at this moment.

**Comment by lezetho** [comment]
@HirziDevs Your thoughts?

**Comment by HirziDevs** [comment]
> @HirziDevs Your thoughts?

I think it's fine? But do it works with the new pterostats?

**Comment by PandeoF1** [comment]
> > @HirziDevs Your thoughts?
> 
> I think it's fine? But do it works with the new pterostats? 

I will try to rebase and test it

**Comment by PandeoF1** [comment]
@HirziDevs Ok so it worked but with the new way of setup that you have introduce. It require to have the config.yaml already setup before starting the bot. (It's not a big problem because the bot will show an error if the config.yaml is not present so it's okay !)
I have also patch the conflict (check the README.md if i haven't made an issue ^^)

**Comment by HirziDevs** [comment]
@PandeoF1 can you please update the code? i did fix the config error issue

**Review by HirziDevs — APPROVED** [review]

**Comment by PandeoF1** [comment]
> @PandeoF1 can you please update the code? i did fix the config error issue

Can you please revert the merge ? I have added a little bit of docs and two lines in the docker compose

**Comment by PandeoF1** [comment]
> > @PandeoF1 can you please update the code? i did fix the config error issue
> 
> Can you please revert the merge ? I have added a little bit of docs and two lines in the docker compose

Or i can make another PR to add the new change if u want

**Comment by HirziDevs** [comment]
> > > @PandeoF1 can you please update the code? i did fix the config error issue
> > 
> > 
> > Can you please revert the merge ? I have added a little bit of docs and two lines in the docker compose
> 
> Or i can make another PR to add the new change if u want

You can create another PR

**Pull request merged**
