### PR TITLE
DIscordJS V-13 With Some Commands

### PR DESCRIPTION
**Pull request by ShreshthTiwari**

### CODE REVIEW

**Comment by nickdevnl** [comment]
@ShreshthTiwari Please use 1024 for mb/gb and not 1000 the rest is working perfectly so this can be merged after that change 
@HirziDevs

**Comment by ShreshthTiwari** [comment]
I did 1000 intentionally
bcz if it is 1001MB or 1023MB
it will show as that and its not looking good
instead it will show 0.9MB

**Comment by nickdevnl** [comment]
Servers count ram/disk in Gbit and not in GB so its better to update it to Gbit so its 1024

**Comment by snaildos** [comment]
Is this PR still maintained?

**Pull request closed without merging**
